Django-Desarrollo/pFuhrmann/pFuhrmann/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from appWeb import views
from django.contrib.auth.views import login, logout

admin.autodiscover()
urlpatterns = patterns('',
    
    # ------ Estadisticas  
    url(r'^eRh/$', 'appWeb.views.estadisticasRepresentantes'),
    url(r'^eRl/$', 'appWeb.views.line'),
    
    url(r'^esta/$', 'appWeb.views.estadisticasMaq'),
    url(r'^esta/(?P<FI>.*)/(?P<FF>.*)/$', 'appWeb.views.estadisticasMaquinarias'),

    # ------ Adm. Login  
    url(r'^login/$', 'appWeb.views.login_user'),
    url(r'^logout/$', 'appWeb.views.logout'),
    url(r'^recoveryPassword/$', 'appWeb.views.recoveryPassword'),
    url(r'^recoveryPassword/(.*)/$', 'appWeb.views.recoveryPassword'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^acercaDe/', 'appWeb.views.acercaDe'),
    url(r'^$','appWeb.views.index'),
    url(r'^index/','appWeb.views.index'),
    url(r'^error_message/','appWeb.views.error_message'),
    url(r'^error_message_404/','appWeb.views.error_message_404'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # ------ Adm. Excel
    url(r'^excelRepresentantes/$', 'appWeb.views.excelRepresentantes'),        
    url(r'^excelProductores/$', 'appWeb.views.excelProductores'),        
    url(r'^excelLotes/$', 'appWeb.views.excelLotes'),        
    url(r'^excelFardos/$', 'appWeb.views.excelFardos'),        

    # ------ Adm. Compra
    url(r'^registrarCompra/$', 'appWeb.views.registrarCompra'),
    url(r'^listadoCompra/$', 'appWeb.views.listadoCompra'),
    url(r'^buscarCompra/(.*)/$', 'appWeb.views.buscarCompra'),
   
    # ------ Adm. Venta
    url(r'^registrarVenta/$', 'appWeb.views.registrarVenta'),
    url(r'^listadoVenta/$', 'appWeb.views.listadoVenta'),
    url(r'^buscarVenta/(.*)/$', 'appWeb.views.buscarVenta'),

    # ------ Adm. PDF
    url(r'^pdfEstancias/$', 'appWeb.views.pdfEstancias'),
    url(r'^pdfCompras/$', 'appWeb.views.pdfCompras'),
    url(r'^pdfVentas/$', 'appWeb.views.pdfVentas'),
    url(r'^pdfRepresentantes/$', 'appWeb.views.pdfRepresentantes'),
    url(r'^pdfProductores/$', 'appWeb.views.pdfProductores'),
    url(r'^pdfOp/$', 'appWeb.views.pdfOp'),

    # ------ Adm. Orden de produccion
    url(r'^registrarOrdenProduccion/$', 'appWeb.views.registrarOrdenProduccion'),
    url(r'^modificarOrdenProduccion/(\d+)/$', 'appWeb.views.modificarOrdenProduccion'),
    url(r'^cancelarOrdenProduccion/(\d+)/$', 'appWeb.views.cancelarOrdenProduccion'),
    url(r'^enviarFaseProduccion/$', 'appWeb.views.enviarFaseProduccion'),
    url(r'^verOrdenProduccion/(\d+)/$', 'appWeb.views.verOrdenProduccion'),
    url(r'^finalizarFaseProduccion/$', 'appWeb.views.finalizarFaseProduccion'),
    url(r'^listadoOrden/$', 'appWeb.views.listadoOrden'),
    url(r'^agregarDetalle/(\d+)/$', 'appWeb.views.mostrarEstancia'),
    url(r'^loteEstancia/(?P<estancia>.*)/(?P<orden>\d+)/$', 'appWeb.views.mostrarLotes'),
    url(r'^fardosLote/(\d+)/$', 'appWeb.views.mostrarFardos'),
    url(r'^agregaDetalleOrden/(?P<campos>.*)/(?P<orden>\d+)/$', 'appWeb.views.agregarDetalle'),
    url(r'^buscarOrden/(.*)/$', 'appWeb.views.buscarOrden'),
    url(r'^commitLoteVenta/(?P<cuadricula>.*)/(?P<orden>\d+)/$', 'appWeb.views.commitLoteVenta'),
    url(r'^agregarLoteVenta/(\d+)/$', 'appWeb.views.agregarLoteVenta'),
    url(r'^commitIniciarFase/(?P<orden>\d+)/(?P<nroSerie>\d+)/$', 'appWeb.views.commitIniciarFase'),
    url(r'^enviarFaseProduccion/(\d+)/$', 'appWeb.views.enviarFaseProduccion'),
    url(r'^finalizarFaseProduccion/(\d+)/$', 'appWeb.views.finalizarFaseProduccion'),

    # ------ Adm. Lotes
    url(r'^registrarLote/$', 'appWeb.views.registrarLote'),
    url(r'^listadoLotes/$', 'appWeb.views.listadoLotes'),
    #url(r'^modificarLote/(\d+)/$', 'appWeb.views.modificarLote'),
    url(r'^eliminarLote/(\d+)/$', 'appWeb.views.eliminarLoteId'),
    url(r'^buscarLote/(.*)/$', 'appWeb.views.buscarLote'),
    
    # ------ Adm. Fardos
    url(r'^registrarFardo/$', 'appWeb.views.registrarFardo'),
    url(r'^listadoFardos/$', 'appWeb.views.listadoFardos'),
    #url(r'^modificarFardo/(\d+)/$', 'appWeb.views.modificarFardo'),
    url(r'^buscarFardo/(.*)/$', 'appWeb.views.buscarFardo'),

    # ------ Adm. Estancias
    url(r'^listadoEstancias/$', 'appWeb.views.listadoEstancias'),
    url(r'^registrarEstancia/$', 'appWeb.views.registrarEstancia'),
    url(r'^modificarEstancia/([\d-]+)/$', 'appWeb.views.modificarEstancia'),
    url(r'^eliminarEstancia/([\d-]+)/$', 'appWeb.views.eliminarEstancia'),
    url(r'^buscarEstancia/(.*)/$', 'appWeb.views.buscarEstancia'),
    
    # ------ Adm. Productor
    url(r'^listadoProductores/$', 'appWeb.views.listadoProductores'),
    url(r'^registrarProductor/$', 'appWeb.views.registrarProductor'),
    url(r'^modificarProductor/([\d-]+)/$', 'appWeb.views.modificarProductor'),
    url(r'^eliminarProductor/([\d-]+)/$', 'appWeb.views.eliminarProductor'),
    url(r'^buscarProductor/(.*)/$', 'appWeb.views.buscarProductor'),

    # ------ Adm. Representante
    url(r'^listadoRepresentante/$', 'appWeb.views.listadoRepresentante'),
    url(r'^registrarRepresentante/$', 'appWeb.views.registrarRepresentante'),
    url(r'^modificarRepresentante/([\d-]+)/$', 'appWeb.views.modificarRepresentante'),
    url(r'^eliminarRepresentante/([\d-]+)/$', 'appWeb.views.eliminarRepresentante'),
    url(r'^buscarRepresentante/(.*)/$', 'appWeb.views.buscarRepresentante'),
    
    # ------ Adm. Maquinaria
    url(r'^listadoMaquinaria/$', 'appWeb.views.listadoMaquinaria'),
    url(r'^registrarMaquinaria/$', 'appWeb.views.registrarMaquinaria'),
    url(r'^modificarMaquinaria/(\d+)$', 'appWeb.views.modificarMaquinaria'),
    url(r'^eliminarMaquinaria/(\d+)/$', 'appWeb.views.eliminarMaquinaria'),
    url(r'^buscarMaquinaria/(.*)/$', 'appWeb.views.buscarMaquinaria'),
)

Django-Desarrollo/pFuhrmann/appWeb/models.py
from django.db import models
from datetime import date

class CompraLote(models.Model):
    class Meta:
        ordering = ['NroCompra']
    NroCompra = models.AutoField(primary_key = True)
    Representante = models.ForeignKey('Representante')
    Estancia = models.ForeignKey('Estancia')
    FechaLlegada = models.DateField()
    
    def __unicode__(self):
        return "%s" % (str(self.Estancia) + " - " + str(self.FechaLlegada))

class Venta(models.Model):
    class Meta:
        ordering = ['NroVenta']
    NroVenta = models.AutoField(primary_key = True)
    LoteVenta = models.OneToOneField('LoteVenta')
    Cliente = models.CharField(max_length=50)
    FechaVenta = models.DateField()

    def __unicode__(self):
        return "%s" % (str(self.Cliente) + " - " + str(self.LoteVenta) + " - " + str(self.FechaVenta))

class Persona(models.Model):
    class Meta:
        ordering = ['Apellido']
    Nombre = models.CharField(max_length=50)
    Apellido = models.CharField(max_length=50)
    DNI = models.CharField(max_length=10, primary_key = True)
    Telefono = models.CharField(max_length=50, null = True, blank = True)
    Email = models.EmailField(null = True, blank = True)
    Baja = models.BooleanField(default=False)
    
    def __unicode__(self):
        return "%s" % str(str(self.Nombre) + " - " + str(self.Apellido) + " - " + str(self.DNI))

class Productor (Persona):
    CUIL = models.CharField(max_length=13, primary_key = True)
        
    def __unicode__(self):
        return "%s" % str(str(self.Nombre) + " " + str(self.Apellido) + " - CUIL: " + str(self.CUIL))

    def tieneEstancia(self):
        if self.estancia:
            return True
        return False

class Representante(Persona): 
    NroLegajo = models.PositiveIntegerField(max_length=50, primary_key = True)
    Zona = models.CharField(max_length=50)
                
    def __unicode__(self):
        return "%s" % str(str(self.Nombre) + " " + str(self.Apellido) + " - DNI: " + str(self.DNI))

    def tieneEstancia(self):
        if self.estancia_set.all():
            return True
        return False

    def tieneCompra(self):
        if self.compra_set.all():
            return True
        return False

class Estancia(models.Model):
    class Meta:
        ordering = ['Nombre']
    
    Nombre = models.CharField(max_length=50)
    CUIT = models.CharField(max_length=13, primary_key = True)
    Provincia = models.CharField(max_length=50)
    Zona = models.CharField(max_length=50)
    Baja = models.BooleanField(default=False)
    Representante = models.ForeignKey('Representante')
    Productor = models.OneToOneField('Productor')
    
    def __unicode__(self):
        return "%s" % str(str(self.Nombre) + " " + str(self.Provincia) + " " + str(self.CUIT) )

    def hasFardos(self):
        for l in self.lote_set.all():
            for f in l.fardo_set.all():
                if f.DetalleOrden == None:
                    return True 
        for l in self.lote_set.all():
            for f in l.fardo_set.all():
                d = f.DetalleOrden
                o = d.OrdenProduccion
                for p in o.produccion_set.all():
                    if p.FechaFin == None:
                        return True

        return False

    
# First, define the Manager subclass.
class BajaLogicaManager(models.Manager):
    def __init__(self, **kwargs):
        super(BajaLogicaManager, self).__init__()
        self.kwargs = kwargs

    def get_queryset(self):
        return super(BajaLogicaManager, self).get_queryset().filter(**self.kwargs)

class Lote(models.Model):
    class Meta:
        ordering = ['NroLote']    
    NroLote = models.AutoField(primary_key = True)
    TipoFardo = models.ForeignKey('TipoFardo')
    CantFardos = models.PositiveIntegerField(max_length=50)
    Peso = models.PositiveIntegerField(max_length=50)
    Baja = models.BooleanField(default=False)
    Compra = models.OneToOneField('CompraLote')
    Estancia = models.ForeignKey('Estancia')
    Cuadricula = models.CharField(max_length=50)

    objects = BajaLogicaManager()                                   # Mostrar todos los objetos
    disponibles = BajaLogicaManager(fardo=None)                 # Mostrar objetos con baja = true

    def __unicode__(self):
        return "%s" % str(str(self.NroLote) + " - " + str(self.TipoFardo.Nombre) + " - " + str(self.Estancia.Nombre))  
  
class Fardo(models.Model):
    class Meta:
        ordering = ['NroFardo']
    NroFardo = models.AutoField(primary_key = True)
    Lote = models.ForeignKey('Lote')
    Peso = models.FloatField()
    Rinde = models.FloatField()
    Finura = models.FloatField()
    CV = models.FloatField()
    AlturaMedia = models.FloatField()
    Romana = models.FloatField()
    DetalleOrden = models.ForeignKey('DetalleOrden', null = True, blank = True)

    def __unicode__(self):
        return u"%d" % self.NroFardo

class TipoFardo(models.Model):
    Nombre = models.CharField(max_length=50, primary_key = True)
    Descripcion = models.CharField(max_length=50)
    Baja = models.BooleanField(default = False)
    
    def __unicode__(self):
        return "%s" % (str(self.Nombre))



# ************************ Orden de Produccion ***************************** #


class OrdenProduccion(models.Model):
    class Meta:
        ordering = ['NroOrden']
    NroOrden = models.AutoField(primary_key = True)
    FechaEmision = models.DateTimeField(auto_now_add = True)
    CantRequerida = models.PositiveIntegerField(max_length=50)
    Servicio = models.ManyToManyField('Servicio', through='Produccion', null = True, blank = True)
    CV = models.FloatField()
    AlturaMedia = models.FloatField()
    Finura = models.FloatField()                                # Medida Micrones
    Romana = models.FloatField()
    Rinde = models.FloatField()
    Finalizada = models.BooleanField(default=False)
    Cancelada = models.BooleanField(default=False)

    def __unicode__(self):
        return u"%s " % self.NroOrden

    def isFinalizada(self):
        return all(map(lambda p: p.FechaFin != None, self.produccion_set.all()))
   
    def fechaFin(self):
        if self.produccion_set.last() != None:
            if self.produccion_set.last().FechaFin != None:
                return self.produccion_set.last().FechaFin
        
        return 'Sin fecha'

    def fechaInicio(self):
        for p in self.produccion_set.all():
            if p.FechaInicio != None:
                return p.FechaInicio
        return 'Sin fecha'

    def maquinaActual(self):
        maquinaActual = 'Sin maquina'  
        for p in self.produccion_set.all():
            if p.FechaInicio != None  and  p.FechaFin == None:
                maquinaActual = p.Maquinaria.NroSerie
        return maquinaActual

    def isProduccion(self):
        return any(map(lambda p: p.FechaInicio != None, self.produccion_set.all())) and any(map(lambda p: p.FechaFin == None, self.produccion_set.all())) 

    def hayFardos(self):
        fardos = Fardo.objects.filter(CV__range = (self.CV - ((self.CV * Config.objects.get_int('CV_%_OK')) / 100), self.CV + ((self.CV * Config.objects.get_int('CV_%_OK')) / 100)), 
                                        AlturaMedia__range = (self.AlturaMedia - ((self.AlturaMedia * Config.objects.get_int('ALTURAMEDIA_%_OK')) / 100), self.AlturaMedia + ((self.AlturaMedia * Config.objects.get_int('ALTURAMEDIA_%_OK')) / 100)), 
                                        Finura__range = (self.Finura - ((self.Finura * Config.objects.get_int('FINURA_%_OK')) / 100), self.Finura + ((self.Finura * Config.objects.get_int('FINURA_%_OK')) / 100)), 
                                        Romana__range = (self.Romana - ((self.Romana * Config.objects.get_int('ROMANA_%_OK')) / 100), self.Romana + ((self.Romana * Config.objects.get_int('ROMANA_%_OK')) / 100)), 
                                        Rinde__range = (self.Rinde - ((self.Rinde * Config.objects.get_int('RINDE_%_OK')) / 100), self.Rinde + ((self.Rinde * Config.objects.get_int('RINDE_%_OK')) / 100)), 
                                        DetalleOrden = None)
        kg = 0
        kgInOrden = 0

        for f in fardos:
            kg = kg + f.Peso

        for d in self.detalleorden_set.all():
            for f in d.fardo_set.all():
                kgInOrden = f.Peso + kgInOrden

        if kg < (self.CantRequerida - kgInOrden):
            return False
        return True

    def needFardos(self):
        kgInOrden = 0

        for d in self.detalleorden_set.all():
            for f in d.fardo_set.all():
                kgInOrden = f.Peso + kgInOrden

        if self.CantRequerida > kgInOrden:
            return True
        return False


    def isLavado(self):
        p = self.produccion_set.get(Servicio = 'Lavado')
        if p.FechaInicio == None:
            return 'No'
        if p.FechaInicio != None and p.FechaFin != None:
            return 'Ok'
        if p.FechaInicio != None and p.FechaFin == None:
            return 'En proceso'
    def isPeinado(self):
        p = self.produccion_set.get(Servicio = 'Peinado')
        if p.FechaInicio == None:
            return 'No'
        if p.FechaInicio != None and p.FechaFin != None:
            return 'Ok'
        if p.FechaInicio != None and p.FechaFin == None:
            return 'En proceso'
    def isCardado(self):
        p = self.produccion_set.get(Servicio = 'Cardado')
        if p.FechaInicio == None:
            return 'No'
        if p.FechaInicio != None and p.FechaFin != None:
            return 'Ok'
        if p.FechaInicio != None and p.FechaFin == None:
            return 'En proceso'
    def isLoteVenta(self):
        if self.loteventa == '':
            return True
        return False

    def isEnviarFase(self):    # Si se puede Iniviar algun fase
        if any(map(lambda p: p.FechaInicio != None and p.FechaFin == None, self.produccion_set.all())):
            return False

Django-Desarrollo/pFuhrmann/templates/Lote/LoteVentaForm.html
<fieldset>
    <legend>                      
       <font color = "Black" size=2 face="Comic Sans MS"><h4>Ubicacion Lote de Venta</h4></font>
    </legend>
    <div class="jumbotron">
            <div class="controls col-md-6">
                <font size=3 face="Comic Sans MS"><label>Cuadricula: </label></font>
            </div>
            <div class="controls col-md-6">
                <input type="text" width = '20px' id = "cuadricula"></input>
            </div>
    </div>
</fieldset>
<h4>Los Datos seran obtenidos de la Orden de Produccion.</h4>

<div class="modal-footer">
    <div class="bootstrap-dialog-footer">
        <div class="bootstrap-dialog-footer-buttons">
            <button class="btn btn-default" onClick="submit({{orden.NroOrden}})" type="Submit" id="agregar">Registrar</button>
            <button class="btn btn-default" data-dismiss='modal' >Salir</button>
        </div>
    </div>  
</div>



<script type="text/javascript">

function submit(orden){
    var cuadri = document.getElementById('cuadricula');

    $.ajax({
        type: 'get',
        dataType: 'html',
        url: '/commitLoteVenta/'+ cuadri.value + '/' + orden,
    });
    $("#agregar").hide();


    BootstrapDialog.show({
        title: 'Aviso',
        cssClass: 'error-dialog',
        message: 'Lote de venta Registrado!',
        type: BootstrapDialog.TYPE_WARNING, 
        buttons: [
            {
                label: 'Aceptar',
                action: function(dialogRef){
                    window.location='/listadoOrden';
                    dialogRef.close();
                }
            }]
    });
}
</script>

Django-Desarrollo/pFuhrmann/templates/Lote/listadoLotes.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block contenido %}

<div class="container">
        <div class="panel panel-yellow">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 10.5px;"> <font size = "5"color = "000000">Listado de lotes</font></h4>
                <div class="btn-group pull-right">
                    <div class="input-group">
                       <div class="btn-group pull-right">
                            <a class="btn btn-default" type="button"  title = "Ayuda" onClick="ayuda('<strong>Ayuda listado lotes</strong>', 'El <strong>listado de lotes</strong> muestra el número de lote, estancia, peso, cantidad de fardos, tipo de fardos y cuadrícula en donde se encuentra el lote.</br><br>Ingrese en <strong>buscar </strong>el número de lote del cual desea obtener información.</br><br>Presione el botón <strong>agregar</strong> para registrar un nuevo lote.</br><br>Presione el botón <strong>salir</strong> para volver al menú principal.</br><br>Presione el botón <strong>modificar</strong> para cambiar datos de un lote.</br><br>Presione el botón <strong>eliminar</strong> para eliminar un lote.</br><br>Presione el botón <strong>excel </strong>para descargar el listado de lotes.</br>')" ><span class="glyphicon glyphicon-question-sign"></span></a>
                        </div>
                        <span class="input-group-btn">
                            <a class="btn btn-default" type="button" title="Buscar: Nro. Lote" onClick="javascript: errorBuscar('/buscarLote/', $('#buscar').val());"><span class="glyphicon glyphicon-search"></span></a>
                        </span>
                        <input type="text" id = "buscar" class="form-control" placeholder="Buscar"></input>
                    </div> 
                </div>
            </div>

            <div class="panel-body">
                <table  class="table table-striped table-bordered table-condensed" id="tableLote">
                    <thead>
                        <tr>
                            <th style="text-align:center;" width="6%">Nro. Lote</th>
                            <th style="text-align:center;" width="10%">Estancia</th>
                            <th style="text-align:center;" width="10%">Peso (Kg)</th>
                            <th style="text-align:center;" width="10%">Cantidad de Fardos</th>
                            <th style="text-align:center;" width="10%">Tipo de Fardo</th>
                            <th style="text-align:center;" width="10%">Cuadricula</th>
                            {% if perms.appWeb.change_lote %}
                                <th style="text-align:center;" width="3%">Modificar</th>
                            {% endif %}
                        </tr>
                        {% for dato in lista %}
                        <tr>
                            <td style="text-align:center;" width="6%" id="nroLote">{{dato.NroLote}}</td>
                            <td style="text-align:center;" width="10%">{{dato.Estancia.Nombre}}</td>
                            <td style="text-align:center;" width="10%">{{dato.Peso}}</td>
                            
                            <td style="text-align:center;" width="10%">{{dato.CantFardos}}</td>
                            <td style="text-align:center;" width="10%">{{dato.TipoFardo.Nombre}}</td>
                            <td style="text-align:center;" width="10%">{{dato.Cuadricula}}</td>
                            {% if perms.appWeb.change_lote %}
                                <td style="text-align:center;" width="3%">
                                <a class="btn btn-default" onClick = "comprobar('/modificarLote/{{dato.NroLote}}', '{{dato.fardo_set.all}}', 'El Lote posee fardos en el Sistema')"><span class="glyphicon glyphicon-edit"></span></a>
                                </td>
                            {% endif %}
                        </tr>

                        {% empty %}
                            <li> No existen Lotes pendientes de cargar Fardos </li>
                        {% endfor %}        
                    </thead>    
                </table>

                <div class="pull-right">
                    <a class="btn btn-default btn-gr" type= "button" onClick="ayuda('Descarga Completa','El listado se encuentra en Descargas')" href="/excelLotes" title = "Excel" >Excel</a>                    {% if perms.appWeb.add_lote %}
                        <a class="btn btn-default btn-gr" type= "button" href="/registrarLote" title = "Agregar Lote" >Agregar</a>
                    {% endif %}
                    <a class="btn btn-default btn-gr" type= "button" href="/index" title = "Salir" >Salir</a>
                </div>    
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
    <script type ="text/javascript"> 

        function comprobar(url, fardos, msg) { 

            if (fardos != '[]'){
                BootstrapDialog.show({
                    title: 'Error',
                    cssClass: 'error-dialog',
                    message: msg,
                    type: BootstrapDialog.TYPE_DANGER, 
                    buttons: [
                        {
                            label: 'Aceptar',
                            action: function(dialogRef){
                                dialogRef.close();
                            }
                        }]
                });
            }
            else{
                window.location=url;
            }
        }

    </script>

{% endblock %}

Django-Desarrollo/pFuhrmann/templates/Lote/registrarLoteForm.html
{% extends 'base.html' %}   
{% load crispy_forms_tags %}

{% block contenido %}
<div class="container">
    
        <div class="panel panel-green">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 10.5px;"> <font size = "5"color = "000000">Registrar lote</font></h4>
                <div class="btn-group pull-right">
                    <a class="btn btn-default" type="button"  title = "Ayuda" onClick="ayuda('<strong>Ayuda registrar lote</strong>','El formulario <strong>registrar lote</strong> solicita el ingreso del peso del lote, compra, cantidad de fardos, tipo de fardos y cuadrícula donde se encuentra el lote.</br><br>Todos los campos son obligatorios.</br><br>Presione el botón <strong>registrar</strong> para agregar un nuevo lote.</br><br>Presione el botón <strong>cancelar</strong> para volver al listado de lotes.</br>')"><span class="glyphicon glyphicon-question-sign"></span></a>
                </div>
            </div>
            <div class="panel-body">
                {% crispy formulario %}
            </div>
        </div>
    </div>
</div>

 
{% endblock %}